console.log("costam");
const openAddHero = () => {
    document.getElementsByTagName('main')[0].innerHTML = ''
    +    '<form class="addHero" >'
    +        '<h2>Dodaj Herosa</h2>'
    +        '<input '
    +            'type="text" '
    +            'placeholder="Nazwa Bohatera" '
    +            'onfocus="this.placeholder = '+'""'+'" '
    +            'onblur="this.placeholder = '+'"Nazwa Bohatera" '
    +            'class="addHero__input addHero__name" '
    +        '/>'
    +        '<input '
    +            'type="text" '
    +            'placeholder="Adres/nazwa zdjęcia" '
    +            'onfocus="this.placeholder = '+'"" '
    +            'onblur="this.placeholder = '+'Adres/nazwa zdjęcia" '
    +            'class="addHero__input addHero__image" '
    +        '/>'
    +        '<input '
    +            'type="number" '
    +            'placeholder="Cena wynajmu /h" '
    +            'onfocus="this.placeholder = '+'"" '
    +            'onblur="this.placeholder = '+'Cena wynajmu /h" '
    +            'class="addHero__input addHero__price" '
    +        '/>'
    +        '<textarea '
    +            'type="text" '
    +            'placeholder="Opis Bohatera" '
    +            'onfocus="this.placeholder = '+'"" '
    +            'onblur="this.placeholder = '+'Opis Bohatera" '
    +            'class="addHero__input addHero__description" '
    +        '></textarea>'
    +        '<button type="button" class="addHero__submit">Submit</button>'
    +  '</form>';
}